# This is a basic workflow to help you get started with Actions
name: cicd-alwaysdata

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "nombranche" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # name of first job
  cicd:
    runs-on: ubuntu-latest
    steps:
    # Steps represent a sequence of tasks that will be executed as part of the job
      - run: echo 'workflow lancé'
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: vérification
        uses: actions/checkout@v4
      - run: echo 'préparation de l intégration avec nodeJS'
      - name: intégration
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '20.9'
      - run: npm install simple-hello-world-example
      - name: push
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVEE }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ssh-mmicastres-sb.alwaysdata.net >> ~/.ssh/known_hosts
          pwd
      - name: Push to Bare Repository
        run: |
          git remote add alwaysdata ssh-mmicastres-sb.alwaysdata.net:/home/mmicastres-sb/node
          pwd
          git push alwaysdata main
        env:
          GIT_SSH_COMMAND: 'ssh -i /home/runner/work/codesandbox-tp-jmp/codesandbox-tp-jmp/.ssh/id_rsa -o StrictHostKeyChecking=no'
